import { restify } from './restify';

// This should eventually be an autogenerated file
export interface NewPet {
    name: string;
    tag?: string;
}

export interface Pet {
    id: number;
    name: string;
    tag?: string;
}

export interface UnknownResponseError {
    code: number;
    message: string;
}

export interface PetsEndpoints {
    put: {
    };
    get: {
        '/pets': {
            options: {
                queryParams: {
                    /** How many items to return at one time (max 100) */
                    limit?: number,
                    /** Tags to filter by */
                    tags?: string[];
                }
            },
            responses: {
                code: 200;
                json: Pet[];
            } | {
                code: number;
                json: UnknownResponseError
            }
        },
        '/pets/{petId}': {
            options: {
                pathParams: {
                    /** The id of the pet to retrieve */
                    'petId': number
                }
            },
            responses: {
                code: 200;
                json: Pet;
            } | {
                code: number;
                json: UnknownResponseError
            }
        },
        '/ping': {
            options: undefined,
            responses: {
                code: 200;
                json: Pet;
            } | {
                code: number;
                json: UnknownResponseError
            }
        }
    };
    post: {
        '/pets': {
            options: {
                requestBody: NewPet
            },
            responses: {
                code: 200;
                json: Pet;
            } | {
                code: number;
                json: UnknownResponseError
            }
        }
    };
}

export default restify<PetsEndpoints>({servers: 'http://192.168.1.11:3000'});